name: Backup MongoDB

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MongoDB tools
        run: sudo apt-get install mongodb-clients

      - name: Backup MongoDB
        run: |
          mongodump --uri mongodb+srv://joemondavid:Apple123@joemonqa.vr6mw67.mongodb.net/joemonT0 --gzip --archive=backup.gz
